CREATE TABLE `rh_err_origin` (
  `batch_no` char(50) NOT NULL DEFAULT '' COMMENT '下发批次号',
  `gid` char(50) NOT NULL COMMENT '自动生成',
  `waybill_no` char(50) DEFAULT NULL COMMENT '运单号',
  `order_id` char(50) DEFAULT NULL COMMENT '订单号',
  `norm_address` varchar(1000) NOT NULL COMMENT '原始地址',
  `povince` char(50) DEFAULT NULL COMMENT '省',
  `cityname` char(50) DEFAULT NULL COMMENT '市',
  `city_code` char(50) DEFAULT NULL COMMENT '城市代码',
  `precision_0` char(50) DEFAULT NULL COMMENT '地理编码精度',
  `addr_total_freq` varchar(50) DEFAULT NULL COMMENT '地址总频次',
  `addr_err_freq` varchar(50) DEFAULT NULL COMMENT '地址错误总频次',
  `addr_errcall_freq` varchar(50) DEFAULT NULL COMMENT '地址错柯频次',
  `addr_rece_differ_freq` varchar(50) DEFAULT NULL COMMENT '地址不一致频次',
  `addr_first_differ_time` varchar(50) DEFAULT NULL COMMENT '地址第一次不一致时间',
  `addr_last_differ_time` varchar(50) DEFAULT NULL COMMENT '地址最后一次不一致时间',
  `addr_first_order_time` varchar(50) DEFAULT NULL COMMENT '地址第一次命中时间',
  `addr_last_order_time` varchar(50) DEFAULT NULL COMMENT '地址最后一次命中时间',
  `addr_first_errcall_time` varchar(50) DEFAULT NULL COMMENT '地址第一次发生错柯时间',
  `addr_last_errcall_time` varchar(50) DEFAULT NULL COMMENT '地址最后一次发生错柯时间',
  `dept_code` char(50) DEFAULT NULL COMMENT '妥投网点',
  `zs_tc` char(50) DEFAULT NULL COMMENT '挖掘真实tc',
  `zs_zc` char(50) DEFAULT NULL COMMENT '挖掘真实zc',
  `zc_code` char(50) DEFAULT NULL COMMENT '网点代码（派件不一致对比标准）',
  `tt_tc` char(50) DEFAULT NULL COMMENT 'tt表tc（收件不一致对比标准）',
  `normalized` char(50) DEFAULT NULL,
  `status_0` char(50) DEFAULT NULL,
  `time_stamp` char(50) DEFAULT NULL,
  `resp_time` char(50) DEFAULT NULL,
  `MATCH_ADDR` varchar(2000) DEFAULT NULL COMMENT '匹配地址',
  `STANDARD` varchar(1000) NOT NULL COMMENT '标准地址',
  `SFLAG` varchar(1000) DEFAULT NULL,
  `rh_x` varchar(1000) DEFAULT NULL COMMENT '融合库x',
  `rh_y` varchar(1000) DEFAULT NULL COMMENT '融合库y',
  `rh_tc` char(50) DEFAULT NULL COMMENT '融合库tc',
  `rh_zc` char(50) DEFAULT NULL COMMENT '融合库zc',
  `rh_status` char(50) DEFAULT NULL COMMENT 'rh库是否正确',
  `GL_LEVEL` char(50) DEFAULT NULL COMMENT '匹配级别',
  `SCORE` varchar(200) NOT NULL,
  `SPLITINFO` varchar(2000) DEFAULT NULL COMMENT '分词',
  `MATCH_INFO` varchar(2000) DEFAULT NULL,
  `FILTER` varchar(200) DEFAULT NULL COMMENT '与融合库关联字段：',
  `MATCH_ID` varchar(3000) DEFAULT NULL,
  `cell1` char(50) DEFAULT NULL,
  `cell3` char(50) DEFAULT NULL,
  `group_group` varchar(2000) NOT NULL COMMENT '大组id',
  `key_index` varchar(50) DEFAULT NULL,
  `adcode` varchar(50) DEFAULT NULL,
  `poi_typecode` varchar(50) DEFAULT NULL,
  `confidence` varchar(200) DEFAULT NULL COMMENT '打分',
  `ts_x` char(50) DEFAULT NULL,
  `ts_y` char(50) DEFAULT NULL,
  `ts_tc` char(50) DEFAULT NULL,
  `ts_zc` char(50) DEFAULT NULL,
  `source` char(50) DEFAULT NULL COMMENT 'source',
  `geosrc` char(50) DEFAULT NULL COMMENT 'geosrc',
  `bq54_tc` char(50) DEFAULT NULL,
  `xiaoge_tc` char(50) DEFAULT NULL,
  `paibanbiao_tc` char(50) DEFAULT NULL,
  `recv_emp_code` char(50) DEFAULT NULL,
  `bq54_x` char(50) DEFAULT NULL,
  `bq54_y` char(50) DEFAULT NULL,
  `keyword` char(100) DEFAULT NULL COMMENT '主体词',
  `src_log` varchar(100) DEFAULT NULL COMMENT '0:收件不一致，1：派件不一致，2：收件挖掘zc不一致，3：派件挖掘zc不一致，4：线上错柯，5：其他',
  `inc_day` char(50) DEFAULT NULL COMMENT '时间',
  `input_day` varchar(10) DEFAULT NULL,
  `is_task` tinyint(1) DEFAULT '0',
  `ck_tag` char(1) DEFAULT NULL COMMENT '0正确, 1不在范围, 2 地址错误, 4 地址已拆除',
  `ck_result` char(1) DEFAULT NULL COMMENT '0包含,1相等,2不同 （标准地址不用更新该字段）',
  `recycle_tm` char(20) DEFAULT NULL COMMENT '回收时间（入库时间 年月日 时分秒）',
  PRIMARY KEY (`gid`),
  KEY `norm_address` (`norm_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
