CREATE TABLE `rh_err_bm_task` (
  `gid` char(50) NOT NULL COMMENT '关联原始表字段',
  `address` varchar(1000) NOT NULL COMMENT '原始地址or标准地址',
  `city_code` char(50) DEFAULT NULL COMMENT '城市代码',
  `zno_code` char(50) DEFAULT NULL COMMENT '网点代码（派件不一致对比标准）',
  `team_code` char(50) DEFAULT NULL COMMENT '融合库tc',
  `split_terms` varchar(2000) DEFAULT NULL COMMENT '分词',
  `source` char(50) DEFAULT 'mapB' COMMENT 'source',
  `keyword` char(100) DEFAULT NULL COMMENT '主体词',
  `priority` char(2) DEFAULT '1',
  `check_type` char(2) DEFAULT '3',
  `type` char(2) DEFAULT NULL COMMENT '原始地址：“3”，标准地址：“1”',
  `prefix` char(50) DEFAULT NULL,
  `ref_poi` char(50) DEFAULT '',
  `right_tc` char(50) DEFAULT NULL,
  `x` char(50) DEFAULT NULL,
  `y` char(50) DEFAULT NULL,
  `distance` char(50) DEFAULT '',
  `right_x` char(50) DEFAULT '',
  `right_y` char(50) DEFAULT '',
  `right_keyword` char(50) DEFAULT '',
  `tracking` char(50) DEFAULT '0',
  `parent_id` varchar(2000) DEFAULT NULL COMMENT '原始地址：group_group,标准地址：null',
  `task_id` char(50) DEFAULT NULL,
  `task_name` char(50) DEFAULT NULL,
  `task_type` char(1) DEFAULT '2',
  `sub_task_type` char(1) DEFAULT '',
  `init_id` char(50) DEFAULT NULL COMMENT '原始地址：null,标准地址gid',
  `init_id_source` char(20) DEFAULT NULL COMMENT '原始地址：“原始地址”，标准地址：“标准地址”',
  `ck_tag` char(1) DEFAULT NULL COMMENT '0正确, 1不在范围, 2 地址错误, 4 地址已拆除',
  `is_finish` char(1) DEFAULT NULL COMMENT 'N 未完成，Y已完成',
  `ck_result` char(1) DEFAULT NULL COMMENT '0包含,1相等,2不同 （标准地址不用更新该字段）',
  `recycle_tm` char(20) DEFAULT NULL COMMENT '回收时间（入库时间 年月日 时分秒）',
  KEY `gid` (`gid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;